### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by rzr** [hyc/BerkeleyDB#1]
https://community.oracle.com/hub/forums/forum.jspa?forumID=271

May it be updated to:
https://en.wikipedia.org/wiki/Berkeley_DB

I am also curious to know if this project can be community maintained at:

https://rzr.github.io/rzr-presentations/docs/abandonware

**Comment by hyc** [comment]
BerkeleyDB is not abandonware, it's still a product on Oracle's web site https://www.oracle.com/database/technologies/related/berkeleydb.html

This repo is just a historical archive of older releases up to 6.0.20. As for the broken link, that's what's in the 6.0.20 Readme, I don't edit any of the contents of this repo. Anyone can find newer releases on Oracle's web site.
